<?php
/**
 * PackageHazMatPackageInformation
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  OpenAPIClientUPSShipping
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Ship
 *
 * The Shipping Package API gives the application many ways to manage the shipment of packages to their destination. # Reference - <a href=\"https://developer.ups.com/api/reference/shipping/business-rules\" target=\"_blank\" rel=\"noopener\">Business Rules</a> - <a href=\"https://developer.ups.com/api/reference/shipping/appendix1\" target=\"_blank\" rel=\"noopener\">Appendix 1</a> - <a href=\"https://developer.ups.com/api/reference/shipping/appendix2\" target=\"_blank\" rel=\"noopener\">Appendix 2</a> - <a href=\"https://developer.ups.com/api/reference/shipping/errors\" target=\"_blank\" rel=\"noopener\">Errors</a> - <a href=\"https://developer.ups.com/api/reference/shipping/faq\" target=\"_blank\" rel=\"noopener\">FAQ</a> - <a href=\"https://developer.ups.com/api/reference/shipping/best-practices\" target=\"_blank\" rel=\"noopener noreferrer\"> Best Practices</a>  <br/><p>Try out UPS APIs with example requests using Postman and learn more about the UPS Postman Collection by visiting our <a href=\"https://developer.ups.com/api/reference/postman/guide\" target=\"_blank\" rel=\"noopener\">Postman Guide</a>. Explore API documentation and sample applications through GitHub.</p>  <a href=\"https://god.gw.postman.com/run-collection/29542085-af2f70b3-405b-4aee-af8d-1eb715e4cebc?action=collection%2Ffork&source=rip_markdown&collection-url=entityId%3D29542085-af2f70b3-405b-4aee-af8d-1eb715e4cebc%26entityType%3Dcollection%26workspaceId%3D7e7595f0-4829-4f9a-aee1-75c126b9d417\" target=\"_blank\" rel=\"noopener noreferrer\">   <img src=\"https://run.pstmn.io/button.svg\" alt=\"Run In Postman\" style=\"width: 128px; height: 32px;\"></a> <a href=\"https://github.com/UPS-API\" target=\"_blank\" rel=\"noopener noreferrer\">   <img src=\"https://www.ups.com/assets/resources/webcontent/images/gitHubButton.svg\" alt=\"Open in GitHub \" style=\"width: 128px; height: 32px;\"> </a>
 *
 * The version of the OpenAPI document: 
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.14.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPIClientUPSShipping\Model;

use \ArrayAccess;
use \OpenAPIClientUPSShipping\ObjectSerializer;

/**
 * PackageHazMatPackageInformation Class Doc Comment
 *
 * @category Class
 * @description Required when number of hazmat containers in a package is greater than 1. It indicates whether all the hazmat materials are kept in a single box or multiple boxes.  Required when number of hazmat container in a package is greater than 1.
 * @package  OpenAPIClientUPSShipping
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class PackageHazMatPackageInformation implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'Package_HazMatPackageInformation';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'allPackedInOneIndicator' => 'string',
        'overPackedIndicator' => 'string',
        'qValue' => 'string',
        'outerPackagingType' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'allPackedInOneIndicator' => null,
        'overPackedIndicator' => null,
        'qValue' => null,
        'outerPackagingType' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'allPackedInOneIndicator' => false,
        'overPackedIndicator' => false,
        'qValue' => false,
        'outerPackagingType' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'allPackedInOneIndicator' => 'AllPackedInOneIndicator',
        'overPackedIndicator' => 'OverPackedIndicator',
        'qValue' => 'QValue',
        'outerPackagingType' => 'OuterPackagingType'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'allPackedInOneIndicator' => 'setAllPackedInOneIndicator',
        'overPackedIndicator' => 'setOverPackedIndicator',
        'qValue' => 'setQValue',
        'outerPackagingType' => 'setOuterPackagingType'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'allPackedInOneIndicator' => 'getAllPackedInOneIndicator',
        'overPackedIndicator' => 'getOverPackedIndicator',
        'qValue' => 'getQValue',
        'outerPackagingType' => 'getOuterPackagingType'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('allPackedInOneIndicator', $data ?? [], null);
        $this->setIfExists('overPackedIndicator', $data ?? [], null);
        $this->setIfExists('qValue', $data ?? [], null);
        $this->setIfExists('outerPackagingType', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if (!is_null($this->container['qValue']) && (mb_strlen($this->container['qValue']) > 3)) {
            $invalidProperties[] = "invalid value for 'qValue', the character length must be smaller than or equal to 3.";
        }

        if (!is_null($this->container['qValue']) && (mb_strlen($this->container['qValue']) < 3)) {
            $invalidProperties[] = "invalid value for 'qValue', the character length must be bigger than or equal to 3.";
        }

        if (!is_null($this->container['outerPackagingType']) && (mb_strlen($this->container['outerPackagingType']) > 255)) {
            $invalidProperties[] = "invalid value for 'outerPackagingType', the character length must be smaller than or equal to 255.";
        }

        if (!is_null($this->container['outerPackagingType']) && (mb_strlen($this->container['outerPackagingType']) < 1)) {
            $invalidProperties[] = "invalid value for 'outerPackagingType', the character length must be bigger than or equal to 1.";
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets allPackedInOneIndicator
     *
     * @return string|null
     */
    public function getAllPackedInOneIndicator()
    {
        return $this->container['allPackedInOneIndicator'];
    }

    /**
     * Sets allPackedInOneIndicator
     *
     * @param string|null $allPackedInOneIndicator Presence/Absence Indicator. Any value is ignored. Presence indicates if multiple, different hazmat/chemicals are contained within one box in a package  When number of Hazmat containers in a package is more than one, either AllPackedInOneIndicator or OverPackedIndicator is needed
     *
     * @return self
     */
    public function setAllPackedInOneIndicator($allPackedInOneIndicator)
    {
        if (is_null($allPackedInOneIndicator)) {
            throw new \InvalidArgumentException('non-nullable allPackedInOneIndicator cannot be null');
        }


        $this->container['allPackedInOneIndicator'] = $allPackedInOneIndicator;

        return $this;
    }

    /**
     * Gets overPackedIndicator
     *
     * @return string|null
     */
    public function getOverPackedIndicator()
    {
        return $this->container['overPackedIndicator'];
    }

    /**
     * Sets overPackedIndicator
     *
     * @param string|null $overPackedIndicator Presence/Absence Indicator. Any value is ignored. Presence indicates that one or more hazmat/chemicals are in separate boxes in a package.  When number of Hazmat containers in a package is more than one, either AllPackedInOneIndicator or OverPackedIndicator is needed
     *
     * @return self
     */
    public function setOverPackedIndicator($overPackedIndicator)
    {
        if (is_null($overPackedIndicator)) {
            throw new \InvalidArgumentException('non-nullable overPackedIndicator cannot be null');
        }


        $this->container['overPackedIndicator'] = $overPackedIndicator;

        return $this;
    }

    /**
     * Gets qValue
     *
     * @return string|null
     */
    public function getQValue()
    {
        return $this->container['qValue'];
    }

    /**
     * Sets qValue
     *
     * @param string|null $qValue When a HazMat shipment specifies AllPackedInOneIndicator and the regulation set for that shipment is IATA, Ship API must require the shipment to specify a Q-Value with exactly one of the following values: 0.1; 0.2; 0.3; 0.4; 0.5; 0.6; 0.7; 0.8; 0.9; 1.0
     *
     * @return self
     */
    public function setQValue($qValue)
    {
        if (is_null($qValue)) {
            throw new \InvalidArgumentException('non-nullable qValue cannot be null');
        }
        if ((mb_strlen($qValue) > 3)) {
            throw new \InvalidArgumentException('invalid length for $qValue when calling PackageHazMatPackageInformation., must be smaller than or equal to 3.');
        }
        if ((mb_strlen($qValue) < 3)) {
            throw new \InvalidArgumentException('invalid length for $qValue when calling PackageHazMatPackageInformation., must be bigger than or equal to 3.');
        }

        $this->container['qValue'] = $qValue;

        return $this;
    }

    /**
     * Gets outerPackagingType
     *
     * @return string|null
     */
    public function getOuterPackagingType()
    {
        return $this->container['outerPackagingType'];
    }

    /**
     * Sets outerPackagingType
     *
     * @param string|null $outerPackagingType This field is used for the Outer Hazmat packaging type.  Ex. FIBERBOARD BOX, WOOD(EN) BOX, PLASTIC JERRICAN, METAL BOX, STEEL DRUM, OTHER, PLASTIC BOX, PLASTIC DRUM, STYROFOAM BOX, CYLINDERS, ENVIROTAINER, PLYWOOD BOX, ALUMINUM DRUM, ALUMINUM CYLINDERS, PLASTIC PAIL, PLYWOOD DRUM, FIBER DRUM, STEEL JERRICAN, ALUMINUM JERRICAN, STEEL BOX, CARTON, ALUMINUM BOX
     *
     * @return self
     */
    public function setOuterPackagingType($outerPackagingType)
    {
        if (is_null($outerPackagingType)) {
            throw new \InvalidArgumentException('non-nullable outerPackagingType cannot be null');
        }
        if ((mb_strlen($outerPackagingType) > 255)) {
            throw new \InvalidArgumentException('invalid length for $outerPackagingType when calling PackageHazMatPackageInformation., must be smaller than or equal to 255.');
        }
        if ((mb_strlen($outerPackagingType) < 1)) {
            throw new \InvalidArgumentException('invalid length for $outerPackagingType when calling PackageHazMatPackageInformation., must be bigger than or equal to 1.');
        }

        $this->container['outerPackagingType'] = $outerPackagingType;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


