<?php
/**
 * ShipmentRequestLabelSpecification
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  OpenAPIClientUPSShipping
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Ship
 *
 * The Shipping Package API gives the application many ways to manage the shipment of packages to their destination. # Reference - <a href=\"https://developer.ups.com/api/reference/shipping/business-rules\" target=\"_blank\" rel=\"noopener\">Business Rules</a> - <a href=\"https://developer.ups.com/api/reference/shipping/appendix1\" target=\"_blank\" rel=\"noopener\">Appendix 1</a> - <a href=\"https://developer.ups.com/api/reference/shipping/appendix2\" target=\"_blank\" rel=\"noopener\">Appendix 2</a> - <a href=\"https://developer.ups.com/api/reference/shipping/errors\" target=\"_blank\" rel=\"noopener\">Errors</a> - <a href=\"https://developer.ups.com/api/reference/shipping/faq\" target=\"_blank\" rel=\"noopener\">FAQ</a> - <a href=\"https://developer.ups.com/api/reference/shipping/best-practices\" target=\"_blank\" rel=\"noopener noreferrer\"> Best Practices</a>  <br/><p>Try out UPS APIs with example requests using Postman and learn more about the UPS Postman Collection by visiting our <a href=\"https://developer.ups.com/api/reference/postman/guide\" target=\"_blank\" rel=\"noopener\">Postman Guide</a>. Explore API documentation and sample applications through GitHub.</p>  <a href=\"https://god.gw.postman.com/run-collection/29542085-af2f70b3-405b-4aee-af8d-1eb715e4cebc?action=collection%2Ffork&source=rip_markdown&collection-url=entityId%3D29542085-af2f70b3-405b-4aee-af8d-1eb715e4cebc%26entityType%3Dcollection%26workspaceId%3D7e7595f0-4829-4f9a-aee1-75c126b9d417\" target=\"_blank\" rel=\"noopener noreferrer\">   <img src=\"https://run.pstmn.io/button.svg\" alt=\"Run In Postman\" style=\"width: 128px; height: 32px;\"></a> <a href=\"https://github.com/UPS-API\" target=\"_blank\" rel=\"noopener noreferrer\">   <img src=\"https://www.ups.com/assets/resources/webcontent/images/gitHubButton.svg\" alt=\"Open in GitHub \" style=\"width: 128px; height: 32px;\"> </a>
 *
 * The version of the OpenAPI document: 
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.14.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPIClientUPSShipping\Model;

use \ArrayAccess;
use \OpenAPIClientUPSShipping\ObjectSerializer;

/**
 * ShipmentRequestLabelSpecification Class Doc Comment
 *
 * @category Class
 * @description Container used to define the properties required by the user to print and/or display the UPS shipping label.  Required for shipment without return service or shipments with PRL return service. Required for Electronic Return Label or Electronic Import Control Label shipments with SubVersion greater than or equal to 1707.
 * @package  OpenAPIClientUPSShipping
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class ShipmentRequestLabelSpecification implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'ShipmentRequest_LabelSpecification';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'labelImageFormat' => '\OpenAPIClientUPSShipping\Model\LabelSpecificationLabelImageFormat',
        'hTTPUserAgent' => 'string',
        'labelStockSize' => '\OpenAPIClientUPSShipping\Model\LabelSpecificationLabelStockSize',
        'instruction' => '\OpenAPIClientUPSShipping\Model\LabelSpecificationInstruction[]',
        'characterSet' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'labelImageFormat' => null,
        'hTTPUserAgent' => null,
        'labelStockSize' => null,
        'instruction' => null,
        'characterSet' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'labelImageFormat' => false,
        'hTTPUserAgent' => false,
        'labelStockSize' => false,
        'instruction' => false,
        'characterSet' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'labelImageFormat' => 'LabelImageFormat',
        'hTTPUserAgent' => 'HTTPUserAgent',
        'labelStockSize' => 'LabelStockSize',
        'instruction' => 'Instruction',
        'characterSet' => 'CharacterSet'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'labelImageFormat' => 'setLabelImageFormat',
        'hTTPUserAgent' => 'setHTTPUserAgent',
        'labelStockSize' => 'setLabelStockSize',
        'instruction' => 'setInstruction',
        'characterSet' => 'setCharacterSet'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'labelImageFormat' => 'getLabelImageFormat',
        'hTTPUserAgent' => 'getHTTPUserAgent',
        'labelStockSize' => 'getLabelStockSize',
        'instruction' => 'getInstruction',
        'characterSet' => 'getCharacterSet'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('labelImageFormat', $data ?? [], null);
        $this->setIfExists('hTTPUserAgent', $data ?? [], null);
        $this->setIfExists('labelStockSize', $data ?? [], null);
        $this->setIfExists('instruction', $data ?? [], null);
        $this->setIfExists('characterSet', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['labelImageFormat'] === null) {
            $invalidProperties[] = "'labelImageFormat' can't be null";
        }
        if (!is_null($this->container['hTTPUserAgent']) && (mb_strlen($this->container['hTTPUserAgent']) > 64)) {
            $invalidProperties[] = "invalid value for 'hTTPUserAgent', the character length must be smaller than or equal to 64.";
        }

        if (!is_null($this->container['hTTPUserAgent']) && (mb_strlen($this->container['hTTPUserAgent']) < 1)) {
            $invalidProperties[] = "invalid value for 'hTTPUserAgent', the character length must be bigger than or equal to 1.";
        }

        if ($this->container['labelStockSize'] === null) {
            $invalidProperties[] = "'labelStockSize' can't be null";
        }
        if (!is_null($this->container['characterSet']) && (mb_strlen($this->container['characterSet']) > 3)) {
            $invalidProperties[] = "invalid value for 'characterSet', the character length must be smaller than or equal to 3.";
        }

        if (!is_null($this->container['characterSet']) && (mb_strlen($this->container['characterSet']) < 3)) {
            $invalidProperties[] = "invalid value for 'characterSet', the character length must be bigger than or equal to 3.";
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets labelImageFormat
     *
     * @return \OpenAPIClientUPSShipping\Model\LabelSpecificationLabelImageFormat
     */
    public function getLabelImageFormat()
    {
        return $this->container['labelImageFormat'];
    }

    /**
     * Sets labelImageFormat
     *
     * @param \OpenAPIClientUPSShipping\Model\LabelSpecificationLabelImageFormat $labelImageFormat labelImageFormat
     *
     * @return self
     */
    public function setLabelImageFormat($labelImageFormat)
    {
        if (is_null($labelImageFormat)) {
            throw new \InvalidArgumentException('non-nullable labelImageFormat cannot be null');
        }
        $this->container['labelImageFormat'] = $labelImageFormat;

        return $this;
    }

    /**
     * Gets hTTPUserAgent
     *
     * @return string|null
     */
    public function getHTTPUserAgent()
    {
        return $this->container['hTTPUserAgent'];
    }

    /**
     * Sets hTTPUserAgent
     *
     * @param string|null $hTTPUserAgent Browser HTTPUserAgent String. This is the preferred way of identifying GIF image type to be generated.  Required if /ShipmentRequest/LabelSpecificationLabelSpecification/LabelImageFormat/Code = Gif. Default to Mozilla/4.5 if this field is missing or has invalid value.
     *
     * @return self
     */
    public function setHTTPUserAgent($hTTPUserAgent)
    {
        if (is_null($hTTPUserAgent)) {
            throw new \InvalidArgumentException('non-nullable hTTPUserAgent cannot be null');
        }
        if ((mb_strlen($hTTPUserAgent) > 64)) {
            throw new \InvalidArgumentException('invalid length for $hTTPUserAgent when calling ShipmentRequestLabelSpecification., must be smaller than or equal to 64.');
        }
        if ((mb_strlen($hTTPUserAgent) < 1)) {
            throw new \InvalidArgumentException('invalid length for $hTTPUserAgent when calling ShipmentRequestLabelSpecification., must be bigger than or equal to 1.');
        }

        $this->container['hTTPUserAgent'] = $hTTPUserAgent;

        return $this;
    }

    /**
     * Gets labelStockSize
     *
     * @return \OpenAPIClientUPSShipping\Model\LabelSpecificationLabelStockSize
     */
    public function getLabelStockSize()
    {
        return $this->container['labelStockSize'];
    }

    /**
     * Sets labelStockSize
     *
     * @param \OpenAPIClientUPSShipping\Model\LabelSpecificationLabelStockSize $labelStockSize labelStockSize
     *
     * @return self
     */
    public function setLabelStockSize($labelStockSize)
    {
        if (is_null($labelStockSize)) {
            throw new \InvalidArgumentException('non-nullable labelStockSize cannot be null');
        }
        $this->container['labelStockSize'] = $labelStockSize;

        return $this;
    }

    /**
     * Gets instruction
     *
     * @return \OpenAPIClientUPSShipping\Model\LabelSpecificationInstruction[]|null
     */
    public function getInstruction()
    {
        return $this->container['instruction'];
    }

    /**
     * Sets instruction
     *
     * @param \OpenAPIClientUPSShipping\Model\LabelSpecificationInstruction[]|null $instruction instruction
     *
     * @return self
     */
    public function setInstruction($instruction)
    {
        if (is_null($instruction)) {
            throw new \InvalidArgumentException('non-nullable instruction cannot be null');
        }
        $this->container['instruction'] = $instruction;

        return $this;
    }

    /**
     * Gets characterSet
     *
     * @return string|null
     */
    public function getCharacterSet()
    {
        return $this->container['characterSet'];
    }

    /**
     * Sets characterSet
     *
     * @param string|null $characterSet Language character set expected on label. Valid values: dan = Danish (Latin-1) nld = Dutch (Latin-1) fin = Finnish (Latin-1) fra = French (Latin-1) deu = German (Latin-1) itl = Italian (Latin-1) nor = Norwegian (Latin-1) pol  = Polish (Latin-2) por = Poruguese (Latin-1) spa = Spanish (Latin-1)  swe = Swedish (Latin-1)  ces = Czech (Latin-2) hun = Hungarian (Latin-2) slk = Slovak (Latin-2) rus = Russian (Cyrillic) tur = Turkish (Latin-5) ron = Romanian (Latin-2) bul = Bulgarian (Latin-2) est = Estonian (Latin-2) ell = Greek (Latin-2) lav = Latvian (Latin-2) lit = Lithuanian (Latin-2) eng = English (Latin-1)  Default is English (Latin-1).
     *
     * @return self
     */
    public function setCharacterSet($characterSet)
    {
        if (is_null($characterSet)) {
            throw new \InvalidArgumentException('non-nullable characterSet cannot be null');
        }
        if ((mb_strlen($characterSet) > 3)) {
            throw new \InvalidArgumentException('invalid length for $characterSet when calling ShipmentRequestLabelSpecification., must be smaller than or equal to 3.');
        }
        if ((mb_strlen($characterSet) < 3)) {
            throw new \InvalidArgumentException('invalid length for $characterSet when calling ShipmentRequestLabelSpecification., must be bigger than or equal to 3.');
        }

        $this->container['characterSet'] = $characterSet;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


