<?php
/**
 * ShipmentShipmentRatingOptions
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  OpenAPIClientUPSShipping
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Ship
 *
 * The Shipping Package API gives the application many ways to manage the shipment of packages to their destination. # Reference - <a href=\"https://developer.ups.com/api/reference/shipping/business-rules\" target=\"_blank\" rel=\"noopener\">Business Rules</a> - <a href=\"https://developer.ups.com/api/reference/shipping/appendix1\" target=\"_blank\" rel=\"noopener\">Appendix 1</a> - <a href=\"https://developer.ups.com/api/reference/shipping/appendix2\" target=\"_blank\" rel=\"noopener\">Appendix 2</a> - <a href=\"https://developer.ups.com/api/reference/shipping/errors\" target=\"_blank\" rel=\"noopener\">Errors</a> - <a href=\"https://developer.ups.com/api/reference/shipping/faq\" target=\"_blank\" rel=\"noopener\">FAQ</a> - <a href=\"https://developer.ups.com/api/reference/shipping/best-practices\" target=\"_blank\" rel=\"noopener noreferrer\"> Best Practices</a>  <br/><p>Try out UPS APIs with example requests using Postman and learn more about the UPS Postman Collection by visiting our <a href=\"https://developer.ups.com/api/reference/postman/guide\" target=\"_blank\" rel=\"noopener\">Postman Guide</a>. Explore API documentation and sample applications through GitHub.</p>  <a href=\"https://god.gw.postman.com/run-collection/29542085-af2f70b3-405b-4aee-af8d-1eb715e4cebc?action=collection%2Ffork&source=rip_markdown&collection-url=entityId%3D29542085-af2f70b3-405b-4aee-af8d-1eb715e4cebc%26entityType%3Dcollection%26workspaceId%3D7e7595f0-4829-4f9a-aee1-75c126b9d417\" target=\"_blank\" rel=\"noopener noreferrer\">   <img src=\"https://run.pstmn.io/button.svg\" alt=\"Run In Postman\" style=\"width: 128px; height: 32px;\"></a> <a href=\"https://github.com/UPS-API\" target=\"_blank\" rel=\"noopener noreferrer\">   <img src=\"https://www.ups.com/assets/resources/webcontent/images/gitHubButton.svg\" alt=\"Open in GitHub \" style=\"width: 128px; height: 32px;\"> </a>
 *
 * The version of the OpenAPI document: 
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.14.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPIClientUPSShipping\Model;

use \ArrayAccess;
use \OpenAPIClientUPSShipping\ObjectSerializer;

/**
 * ShipmentShipmentRatingOptions Class Doc Comment
 *
 * @category Class
 * @description ShipmentRatingOptions container.
 * @package  OpenAPIClientUPSShipping
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class ShipmentShipmentRatingOptions implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'Shipment_ShipmentRatingOptions';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'negotiatedRatesIndicator' => 'string',
        'fRSShipmentIndicator' => 'string',
        'rateChartIndicator' => 'string',
        'tPFCNegotiatedRatesIndicator' => 'string',
        'userLevelDiscountIndicator' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'negotiatedRatesIndicator' => null,
        'fRSShipmentIndicator' => null,
        'rateChartIndicator' => null,
        'tPFCNegotiatedRatesIndicator' => null,
        'userLevelDiscountIndicator' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'negotiatedRatesIndicator' => false,
        'fRSShipmentIndicator' => false,
        'rateChartIndicator' => false,
        'tPFCNegotiatedRatesIndicator' => false,
        'userLevelDiscountIndicator' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'negotiatedRatesIndicator' => 'NegotiatedRatesIndicator',
        'fRSShipmentIndicator' => 'FRSShipmentIndicator',
        'rateChartIndicator' => 'RateChartIndicator',
        'tPFCNegotiatedRatesIndicator' => 'TPFCNegotiatedRatesIndicator',
        'userLevelDiscountIndicator' => 'UserLevelDiscountIndicator'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'negotiatedRatesIndicator' => 'setNegotiatedRatesIndicator',
        'fRSShipmentIndicator' => 'setFRSShipmentIndicator',
        'rateChartIndicator' => 'setRateChartIndicator',
        'tPFCNegotiatedRatesIndicator' => 'setTPFCNegotiatedRatesIndicator',
        'userLevelDiscountIndicator' => 'setUserLevelDiscountIndicator'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'negotiatedRatesIndicator' => 'getNegotiatedRatesIndicator',
        'fRSShipmentIndicator' => 'getFRSShipmentIndicator',
        'rateChartIndicator' => 'getRateChartIndicator',
        'tPFCNegotiatedRatesIndicator' => 'getTPFCNegotiatedRatesIndicator',
        'userLevelDiscountIndicator' => 'getUserLevelDiscountIndicator'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('negotiatedRatesIndicator', $data ?? [], null);
        $this->setIfExists('fRSShipmentIndicator', $data ?? [], null);
        $this->setIfExists('rateChartIndicator', $data ?? [], null);
        $this->setIfExists('tPFCNegotiatedRatesIndicator', $data ?? [], null);
        $this->setIfExists('userLevelDiscountIndicator', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets negotiatedRatesIndicator
     *
     * @return string|null
     */
    public function getNegotiatedRatesIndicator()
    {
        return $this->container['negotiatedRatesIndicator'];
    }

    /**
     * Sets negotiatedRatesIndicator
     *
     * @param string|null $negotiatedRatesIndicator Negotiated Rates option indicator. If the indicator is present and the Shipper is authorized then Negotiated Rates should be returned in the response.  Negotiated Rates are of two types Account Based Rates (ABR) and Web Discount Rates. Negotiated Rates are only returned for qualified Shipper Account Numbers.   Eligibility is determined using the combination of UserId and the Shipper's Shipper Account Number. If the user is qualified, both Published rates and Negotiated rates are returned to the user. If the UserId and Shipper Account   Number are not qualified for Negotiated rates, a warning message is returned that indicates ineligibility and only the Published rates are returned in the response. As per discount eligibility of user, negotiated rates in the response may contain ABR or Web discount rates.
     *
     * @return self
     */
    public function setNegotiatedRatesIndicator($negotiatedRatesIndicator)
    {
        if (is_null($negotiatedRatesIndicator)) {
            throw new \InvalidArgumentException('non-nullable negotiatedRatesIndicator cannot be null');
        }


        $this->container['negotiatedRatesIndicator'] = $negotiatedRatesIndicator;

        return $this;
    }

    /**
     * Gets fRSShipmentIndicator
     *
     * @return string|null
     */
    public function getFRSShipmentIndicator()
    {
        return $this->container['fRSShipmentIndicator'];
    }

    /**
     * Sets fRSShipmentIndicator
     *
     * @param string|null $fRSShipmentIndicator Ground Freight Pricing Rates option indicator. If the Ground Freight Pricing Shipment indicator is enabled and Shipper number is authorized then Ground Freight Pricing rates should be returned in the response.  The Shipper account number must be qualified to receive Ground Freight Pricing Density Based Shipment rates. Only the Shipper account number taken from /ShipmentRequest/Shipment/FRSPaymentInformation/AccountNumber is used when checking qualification for Ground Freight Pricing Density Based rates.
     *
     * @return self
     */
    public function setFRSShipmentIndicator($fRSShipmentIndicator)
    {
        if (is_null($fRSShipmentIndicator)) {
            throw new \InvalidArgumentException('non-nullable fRSShipmentIndicator cannot be null');
        }


        $this->container['fRSShipmentIndicator'] = $fRSShipmentIndicator;

        return $this;
    }

    /**
     * Gets rateChartIndicator
     *
     * @return string|null
     */
    public function getRateChartIndicator()
    {
        return $this->container['rateChartIndicator'];
    }

    /**
     * Sets rateChartIndicator
     *
     * @param string|null $rateChartIndicator RateChartIndicator, if present in request, response will contain RateChart element.
     *
     * @return self
     */
    public function setRateChartIndicator($rateChartIndicator)
    {
        if (is_null($rateChartIndicator)) {
            throw new \InvalidArgumentException('non-nullable rateChartIndicator cannot be null');
        }


        $this->container['rateChartIndicator'] = $rateChartIndicator;

        return $this;
    }

    /**
     * Gets tPFCNegotiatedRatesIndicator
     *
     * @return string|null
     */
    public function getTPFCNegotiatedRatesIndicator()
    {
        return $this->container['tPFCNegotiatedRatesIndicator'];
    }

    /**
     * Sets tPFCNegotiatedRatesIndicator
     *
     * @param string|null $tPFCNegotiatedRatesIndicator This indicator applies for a third party (3P) / Freight collect (FC) shipment only.   For 3P/FC shipment if the shipper wishes to request for the negotiated rates of the third party then this indicator should be included in the request.   If authorized the 3P/FC negotiated rates will be applied to the shipment and rates will be returned in response.
     *
     * @return self
     */
    public function setTPFCNegotiatedRatesIndicator($tPFCNegotiatedRatesIndicator)
    {
        if (is_null($tPFCNegotiatedRatesIndicator)) {
            throw new \InvalidArgumentException('non-nullable tPFCNegotiatedRatesIndicator cannot be null');
        }


        $this->container['tPFCNegotiatedRatesIndicator'] = $tPFCNegotiatedRatesIndicator;

        return $this;
    }

    /**
     * Gets userLevelDiscountIndicator
     *
     * @return string|null
     */
    public function getUserLevelDiscountIndicator()
    {
        return $this->container['userLevelDiscountIndicator'];
    }

    /**
     * Sets userLevelDiscountIndicator
     *
     * @param string|null $userLevelDiscountIndicator If this indicator is present user level discount will be applied to rates if applicable  Conditions checked: This indicator should be present Shipper number should not be present User should be eligible for user level discount
     *
     * @return self
     */
    public function setUserLevelDiscountIndicator($userLevelDiscountIndicator)
    {
        if (is_null($userLevelDiscountIndicator)) {
            throw new \InvalidArgumentException('non-nullable userLevelDiscountIndicator cannot be null');
        }


        $this->container['userLevelDiscountIndicator'] = $userLevelDiscountIndicator;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


